import { useMemo } from 'react';

const usePDFDocument = (coverLetter, options = {}) => {
  const {
    title = 'Cover Letter',
    author = 'Generated by AI Cover Letter Tool',
    subject = 'Cover Letter Document',
    keywords = 'cover letter, job application',
    creator = 'AI Cover Letter Generator'
  } = options;

  const documentProps = useMemo(() => ({
    title,
    author,
    subject,
    keywords,
    creator,
    producer: 'React-PDF',
    creationDate: new Date(),
    modificationDate: new Date()
  }), [title, author, subject, keywords, creator]);

  const pageProps = useMemo(() => ({
    size: 'A4',
    orientation: 'portrait',
    wrap: true
  }), []);

  const validateContent = (content) => {
    if (!content || typeof content !== 'string') {
      return false;
    }
    return content.trim().length > 0;
  };

  const getFileName = (companyName) => {
    const sanitizedCompany = companyName 
      ? companyName.replace(/[^a-zA-Z0-9]/g, '_')
      : 'Company';
    const timestamp = new Date().toISOString().split('T')[0];
    return `Cover_Letter_${sanitizedCompany}_${timestamp}.pdf`;
  };

  return {
    documentProps,
    pageProps,
    validateContent,
    getFileName,
    isValid: validateContent(coverLetter)
  };
};

export default usePDFDocument;
